FROM ubuntu:18.04
MAINTAINER David Whiting <david.whiting@h2o.ai>

ENV RSTUDIO_VERSION=1.2.1335
ENV CONDA_HOME=/home/h2o/.local/miniconda3

ENV H2O_BRANCH_NAME=rel-yates
ENV H2O_MAJOR_VERSION=3.24.0
ENV H2O_BUILD_NUMBER=5

# To keep tzdata from requesting time zones interactively
ENV DEBIAN_FRONTEND=noninteractive

## Linux
RUN \
  apt-get -y update && \
  apt-get -y install \
    apt-transport-https \
    apt-utils \
    software-properties-common \
    bzip2 \
    cpio \
    curl \
    dirmngr \
    gdebi-core \
    git \
    libcurl4-nss-dev \
    locales \
    net-tools \
    sudo \
    vim \
    wget \
    zip 

RUN \
  locale-gen en_US.UTF-8 && \
  update-locale LANG=en_US.UTF-8

# Java8
RUN \
  apt-get -y install \
    openjdk-8-jre \
    openjdk-8-jdk

# R 3.6 Install
RUN \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 && \
  echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" >> /etc/apt/sources.list && \
  apt-get -y update && \
  apt-get -y install \
    r-base \
    r-base-dev && \
  R -e 'chooseCRANmirror(graphics=FALSE, ind=1);install.packages(c("RCurl","jsonlite","ggplot2"));' && \
  mkdir -p /usr/local/lib/R/site-library && \
  chmod 777 /usr/local/lib/R/site-library

# RStudio Install
ENV RSTUDIO=rstudio-server-${RSTUDIO_VERSION}-amd64.deb
RUN \
  wget https://download2.rstudio.org/server/trusty/amd64/${RSTUDIO} && \
  gdebi --non-interactive ${RSTUDIO} && \
  echo "server-app-armor-enabled=0" >> /etc/rstudio/rserver.conf && \
  rm ${RSTUDIO}

# Log directory used by run.sh
RUN \
  mkdir /log && \
  chmod o+w /log


# ----- USER H2O -----

# h2o user
RUN \
  useradd -ms /bin/bash h2o && \
  usermod -a -G sudo h2o && \
  echo "h2o:h2o" | chpasswd && \
  echo 'h2o ALL=NOPASSWD: ALL' >> /etc/sudoers

USER h2o
WORKDIR /home/h2o

# Install Miniconda
ENV MINICONDA_FILE=Miniconda3-latest-Linux-x86_64.sh
ENV CONDA=${CONDA_HOME}/bin/conda

RUN \
  wget https://repo.anaconda.com/miniconda/${MINICONDA_FILE} && \
  bash ${MINICONDA_FILE} -b -p ${CONDA_HOME} && \
  ${CONDA} update -n base -c defaults conda && \
  rm ${MINICONDA_FILE} && \
  ${CONDA} create -y --name h2o python=3.6 anaconda

# Install H2O
# http://h2o-release.s3.amazonaws.com/h2o/rel-yates/3/h2o-3.24.0.5.zip
ENV H2O_S3_PATH=http://h2o-release.s3.amazonaws.com/h2o
ENV H2O_PROJECT_VERSION=${H2O_MAJOR_VERSION}.${H2O_BUILD_NUMBER}
ENV H2O_DIRECTORY=h2o-${H2O_PROJECT_VERSION}
RUN \
  wget ${H2O_S3_PATH}/${H2O_BRANCH_NAME}/${H2O_BUILD_NUMBER}/h2o-${H2O_PROJECT_VERSION}.zip && \
  unzip ${H2O_DIRECTORY}.zip && \
  rm ${H2O_DIRECTORY}.zip && \
  bash -c "source ${CONDA_HOME}/bin/activate h2o && pip install ${H2O_DIRECTORY}/python/h2o*.whl" && \
  R CMD INSTALL ${H2O_DIRECTORY}/R/h2o*.gz && \
  rm -rf ${H2O_DIRECTORY}

