
######################################################################
# ADD CONTENT FOR COURSEWORK HERE
######################################################################

COPY --chown=h2o contents/data data
COPY --chown=h2o contents/coursework coursework 

#####################################################################

# ----- RUN INFORMATION -----

USER h2o
WORKDIR /home/h2o
ENV JAVA_HOME=/usr

ENTRYPOINT ["/run.sh"]

EXPOSE 54321
EXPOSE 54327
EXPOSE 8888
EXPOSE 8787
EXPOSE 8080
EXPOSE 4040
