FROM ubuntu:18.04
MAINTAINER David Whiting <david.whiting@h2o.ai>

ENV RSTUDIO_VERSION=1.2.1335

## Linux
RUN \
  apt-get -y update && \
  apt-get -y install \
    apt-transport-https \
    apt-utils \
    software-properties-common \
    bzip2 \
    cpio \
    curl \
    dirmngr \
    gdebi-core \
    git \
    libcurl4-nss-dev \
    locales \
    net-tools \
    sudo \
    vim \
    wget \
    zip \
    python-software-properties

RUN \
  locale-gen en_US.UTF-8 && \
  update-locale LANG=en_US.UTF-8

# Java8
RUN \
  apt-get -y install \
    openjdk-8-jre \
    openjdk-8-jdk

# R 3.6 Install
RUN \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 && \
  echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" >> /etc/apt/sources.list && \
  apt-get -y update && \
  apt-get -y install \
    r-base \
    r-base-dev && \
  R -e 'chooseCRANmirror(graphics=FALSE, ind=1);install.packages(c("RCurl","jsonlite","ggplot2"));' && \
  mkdir -p /usr/local/lib/R/site-library && \
  chmod 777 /usr/local/lib/R/site-library

# RStudio Install
ENV RSTUDIO=rstudio-server-${RSTUDIO_VERSION}-amd64.deb
RUN \
  wget https://download2.rstudio.org/server/trusty/amd64/${RSTUDIO} && \
  gdebi --non-interactive ${RSTUDIO} && \
  echo "server-app-armor-enabled=0" >> /etc/rstudio/rserver.conf && \
  rm ${RSTUDIO}

# Log directory used by run.sh
RUN \
  mkdir /log && \
  chmod o+w /log
