FROM step1
MAINTAINER David Whiting <david.whiting@h2o.ai>

ENV CONDA_HOME=/usr/local/miniconda3
ENV MINICONDA_FILE=Miniconda3-latest-Linux-x86_64.sh
ENV CONDA=${CONDA_HOME}/bin/conda
RUN \
  wget https://repo.anaconda.com/miniconda/${MINICONDA_FILE} && \
  bash ${MINICONDA_FILE} -b -p ${CONDA_HOME} && \
  ${CONDA} update -n base -c defaults conda && \
  ${CONDA} create -y --name h2o python=3.6 anaconda && \
  rm ${MINICONDA_FILE}