FROM ubuntu:16.04
MAINTAINER David Whiting <david.whiting@h2o.ai>

## Linux
RUN \
  apt-get -y update && \
  apt-get -y install \
    apt-transport-https \
    apt-utils \
    software-properties-common \
    bzip2 \
    cpio \
    curl \
    dirmngr \
    gdebi-core \
    git \
    libcurl4-nss-dev \
    locales \
    net-tools \
    sudo \
    vim \
    wget \
    zip \
    python-software-properties

RUN \
  locale-gen en_US.UTF-8 && \
  update-locale LANG=en_US.UTF-8

# Java8
RUN \
  apt-get -y install \
    openjdk-8-jre \
    openjdk-8-jdk