FROM step3
MAINTAINER David Whiting <david.whiting@h2o.ai>

ENV CONDA_HOME=/home/h2o/bin/miniconda3
ENV CONDA=${CONDA_HOME}/bin/conda

ENV H2O_BRANCH_NAME=rel-yates
ENV H2O_MAJOR_VERSION=3.24.0
ENV H2O_BUILD_NUMBER=5

RUN \
  ${CONDA} create -y --name h2o python=3.6 anaconda

# Install H2O
# http://h2o-release.s3.amazonaws.com/h2o/rel-yates/3/h2o-3.24.0.5.zip
ENV H2O_S3_PATH=http://h2o-release.s3.amazonaws.com/h2o
ENV H2O_PROJECT_VERSION=${H2O_MAJOR_VERSION}.${H2O_BUILD_NUMBER}
ENV H2O_DIRECTORY=h2o-${H2O_PROJECT_VERSION}
RUN \
  wget ${H2O_S3_PATH}/${H2O_BRANCH_NAME}/${H2O_BUILD_NUMBER}/h2o-${H2O_PROJECT_VERSION}.zip && \
  unzip ${H2O_DIRECTORY}.zip && \
  rm ${H2O_DIRECTORY}.zip && \
  bash -c "source ${CONDA_HOME}/bin/activate h2o && pip install ${H2O_DIRECTORY}/python/h2o*.whl" && \
  R CMD INSTALL ${H2O_DIRECTORY}/R/h2o*.gz