FROM ubuntu:18.04
MAINTAINER David Whiting <david.whiting@h2o.ai>

## Updates to make:
## 1. Change ENV to ARG where possible
##    - $SPARK_HOME is ENV
## 2. Optimize RUN commands to minimize layers
##

ARG BASE=/home/h2o/.local

ARG CONDA_HOME=${BASE}/miniconda3
ENV SPARK_HOME=${BASE}/spark
ARG SPARKLING_WATER_HOME=${BASE}/sparkling-water

##############################
## Versioning information

ARG RSTUDIO_VERSION=1.2.1335

ARG H2O_BRANCH_NAME=yates
ARG H2O_MAJOR_VERSION=3.24.0
ARG H2O_BUILD_NUMBER=5

ARG SPARK_VERSION=2.4.3
ARG SPARK_HADOOP_VERSION=2.7

ARG SPARKLING_WATER_BRANCH_NUMBER=2.4
ARG SPARKLING_WATER_BUILD_NUMBER=13

##### DON'T CHANGE ENV BELOW ############

# To keep tzdata from requesting time zones interactively
ARG DEBIAN_FRONTEND=noninteractive

ARG RSTUDIO=rstudio-server-${RSTUDIO_VERSION}-amd64.deb

ARG MINICONDA_FILE=Miniconda3-latest-Linux-x86_64.sh
ARG CONDA=${CONDA_HOME}/bin/conda

ARG H2O_S3_PATH=http://h2o-release.s3.amazonaws.com/h2o
ARG H2O_PROJECT_VERSION=${H2O_MAJOR_VERSION}.${H2O_BUILD_NUMBER}
ARG H2O_DIRECTORY=h2o-${H2O_PROJECT_VERSION}

ARG SPARK_PATH=https://www-us.apache.org/dist/spark
ARG SPARK_DIRECTORY=spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}

ARG SPARKLING_WATER_PATH=http://h2o-release.s3.amazonaws.com/sparkling-water
ARG SPARKLING_WATER_BRANCH_NAME=rel-${SPARKLING_WATER_BRANCH_NUMBER}
ARG SPARKLING_WATER_PROJECT_VERSION=${SPARKLING_WATER_BRANCH_NUMBER}.${SPARKLING_WATER_BUILD_NUMBER}
ARG SPARKLING_WATER_DIRECTORY=sparkling-water-${SPARKLING_WATER_PROJECT_VERSION}

#########################################

## Linux
RUN \
  apt-get -y update \
  && apt-get -y install \
        apt-transport-https \
        apt-utils \
        software-properties-common \
        bzip2 \
        cpio \
        curl \
        dirmngr \
        gdebi-core \
        git \
        libcurl4-nss-dev \
        locales \
        net-tools \
        sudo \
        vim \
        wget \
        zip \
  && locale-gen en_US.UTF-8 \
  && update-locale LANG=en_US.UTF-8 \
  # Install Java 8
  && apt-get -y install \
        openjdk-8-jre \
        openjdk-8-jdk \
  # Install R 3.6
  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 \
  && echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" >> /etc/apt/sources.list \
  && apt-get -y update  \
  && apt-get -y install \
        r-base \
        r-base-dev \
  && R -e 'chooseCRANmirror(graphics=FALSE, ind=1);install.packages(c("RCurl","jsonlite","ggplot2"));' \
  && mkdir -p /usr/local/lib/R/site-library \
  && chmod 777 /usr/local/lib/R/site-library \
  # RStudio Install
  && wget https://download2.rstudio.org/server/trusty/amd64/${RSTUDIO} \
  && gdebi --non-interactive ${RSTUDIO} \
  && echo "server-app-armor-enabled=0" >> /etc/rstudio/rserver.conf \
  && rm ${RSTUDIO} \
  # Log directory used by run.sh
  && mkdir /log \
  && chmod o+w /log

# ----- USER H2O -----

# h2o user
RUN \
  useradd -ms /bin/bash h2o && \
  usermod -a -G sudo h2o && \
  echo "h2o:h2o" | chpasswd && \
  echo 'h2o ALL=NOPASSWD: ALL' >> /etc/sudoers

USER h2o
WORKDIR /home/h2o

RUN \
  # Install Miniconda
  wget https://repo.anaconda.com/miniconda/${MINICONDA_FILE} \
  && bash ${MINICONDA_FILE} -b -p ${CONDA_HOME} \
  && ${CONDA} update -n base -c defaults conda \
  && rm ${MINICONDA_FILE} \
  && ${CONDA} create -y --name h2o python=3.6 anaconda \
  # Install H2O
  && wget ${H2O_S3_PATH}/rel-${H2O_BRANCH_NAME}/${H2O_BUILD_NUMBER}/h2o-${H2O_PROJECT_VERSION}.zip \
  && unzip ${H2O_DIRECTORY}.zip \
  && rm ${H2O_DIRECTORY}.zip \
  && bash -c "source ${CONDA_HOME}/bin/activate h2o && pip install ${H2O_DIRECTORY}/python/h2o*.whl" \
  && R CMD INSTALL ${H2O_DIRECTORY}/R/h2o*.gz \
  && rm -rf ${H2O_DIRECTORY} \
  ## Create pysparkling
  && ${CONDA} create -y --name pysparkling python=2.7 anaconda \
  # Spark
  && mkdir -p ${SPARK_HOME} \
  && wget ${SPARK_PATH}/spark-${SPARK_VERSION}/${SPARK_DIRECTORY}.tgz \
  && tar zxvf ${SPARK_DIRECTORY}.tgz -C ${SPARK_HOME} --strip-components 1 \
  && rm ${SPARK_DIRECTORY}.tgz \
  && bash -c "source ${CONDA_HOME}/bin/activate pysparkling && pip install tabulate future colorama" \
  # Sparkling Water  
  && wget ${SPARKLING_WATER_PATH}/${SPARKLING_WATER_BRANCH_NAME}/${SPARKLING_WATER_BUILD_NUMBER}/${SPARKLING_WATER_DIRECTORY}.zip \
  && unzip ${SPARKLING_WATER_DIRECTORY}.zip \
  && mv ${SPARKLING_WATER_DIRECTORY} ${SPARKLING_WATER_HOME} \
  && rm ${SPARKLING_WATER_DIRECTORY}.zip \
  # Create jupyter notebook with h2o login token
  && ${CONDA_HOME}/envs/h2o/bin/jupyter notebook --generate-config \
  && sed -i "s/#c.NotebookApp.token = '<generated>'/c.NotebookApp.token = 'h2o'/" /home/h2o/.jupyter/jupyter_notebook_config.py \
  # Create pyspark
  && ${CONDA_HOME}/envs/pysparkling/bin/ipython profile create pyspark

COPY --chown=h2o conf/pyspark/00-pyspark-setup.py /home/h2o/.ipython/profile_pyspark/startup/
COPY --chown=h2o conf/pyspark/kernel.json ${CONDA_HOME}/envs/h2o/share/jupyter/kernels/pyspark/