FROM step2
MAINTAINER David Whiting <david.whiting@h2o.ai>

ENV CONDA_HOME=/usr/local/miniconda3
ENV RSTUDIO_VERSION=1.2.1335

# R 3.6 Install
RUN \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 && \
  echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" >> /etc/apt/sources.list && \
  apt-get -y update && \
  apt-get -y install \
    r-base \
    r-base-dev && \
  R -e 'chooseCRANmirror(graphics=FALSE, ind=1);install.packages(c("RCurl","jsonlite","ggplot2"));' && \
  mkdir -p /usr/local/lib/R/site-library && \
  chmod 777 /usr/local/lib/R/site-library

# RStudio Install
ENV RSTUDIO=rstudio-server-${RSTUDIO_VERSION}-amd64.deb
RUN \
  wget https://download2.rstudio.org/server/trusty/amd64/${RSTUDIO} && \
  gdebi --non-interactive ${RSTUDIO} && \
  echo "server-app-armor-enabled=0" >> /etc/rstudio/rserver.conf && \
  rm ${RSTUDIO}


